SELECT
    A1.AC_NO AS ACCOUNT,
    A1.CUST_NO AS CUSTOMER_NO,
    NULL AS CUSTOMER_NAME1,
    NULL AS RM,
    NULL AS RM_DESC,
    NULL AS CUSTOMER_CATEGORY,
    A1.GL,
    (
      SELECT
        NVL(A1.ACC.AC_DESC, 0) AS qqq,
        A1.GL
      FROM
        CORE.DIM_ACCOUNT ACC
      WHERE
        ACC.AC_NO = A1.GL
        AND V_REP_DATE BETWEEN ACC.DATE_FROM
        AND ACC.DATE_TO
    ) AS GL_DESC,
    A1.BRANCH_CODE,
    A1.CCY,
    DECODE(A1.CCY, 'JOD', A1.LCY_AMT, 0) AS JOD,
    DECODE(A1.CCY, 'JOD', 0, A1.LCY_AMT) AS FCY,
    A1.TYPE,
    A1.ACCOUNT_CLASS,
    0 AS CREDIT_INT_RATE,
    0 AS DEBIT_INT_RATE,
    NULL AS GENDER,
    NULL AS NATIONALITY,
    NULL AS ECONOMIC_SECTOR,
    NULL AS ECONOMIC_SECTOR_DESC,
    NULL AS CIF_STATUS,
    NULL AS COMMERCIAL_SECTOR,
    NULL AS COMMERCIAL_SECTOR_DESC,
    NULL AS RESIDENT,
    A1.START_DATE,
    A1.MATURITY_DATE,
    0 OVERDUE_PRINCIPAL_LCY,
    0 OVERDUE_INT_COMM_LCY,
    NULL AS ISIC_ECONOMIC_SECTOR,
    NULL AS ISIC_ECONOMIC_SECTOR_DESC,
    DECODE(A1.CCY, 'JOD', A1.LCY_AMT, A1.AMT) AS AMT,
    NULL AS AVG_ACY_YTD,
    NULL AS AVG_ACY_MTD,
    NULL AS AVG_ACY_STD,
    NULL AS AVG_LCY_YTD,
    NULL AS AVG_LCY_MTD,
    NULL AS AVG_LCY_STD,
    0 AS NUMBER_OF_DUEDAY,
    DECODE(A1.CCY, 'JOD', A1.LCY_AMT, 0) + DECODE(A1.CCY, 'JOD', 0, A1.LCY_AMT) AS TOTAL,
    NULL AS RM_SEGMENT,
    CASE
      WHEN GL IN ('014120001', '014110036') THEN 'Bills And Notes Discounted'
      WHEN GL IN ('014110001', '014110004') THEN 'Car Loans'
      WHEN GL IN ('014110016', '014110015', '014110019') THEN 'Cards'
      WHEN GL IN ('014110006') THEN 'Housing Loans'
      WHEN GL IN ('014110021') THEN 'Overdraft Facilities'
      WHEN GL LIKE ('022%') THEN 'Overdrawn'
      WHEN GL IN (
        '014110012',
        '014110013',
        '014110011',
        '014110043'
      ) THEN 'Personal Loans'
      WHEN GL IN ('014110031') THEN 'Revolving Loans'
      WHEN GL IN ('014110041') THEN 'Syndicated Loans'
      WHEN GL IN ('014110026') THEN 'Term Loans'
      ELSE 'Other Loans'
    END AS SUB_TYPE,
    DM.BRANCH AS BRANCH_NAME,
    DM.DISTRICT_MANAGER,
    NULL AS DORMANT,
    'A' AS ACC_STATUS,
    NULL AS CORPORATE_GENDER,
    NULL AS AMOUNT_DISBURSED,
    NULL AS AMOUNT_DISBURSED_LCY,
    NULL AS BULLETIN_RATE_RETAIL,
    NULL AS IBNY_ACC,
    NULL AS IBNY_ACC_RATE,
    NULL AS AVG_ACY_YTD_PREV_MONTH,
    NULL AS AVG_ACY_MTD_PREV_MONTH,
    NULL AS AVG_LCY_YTD_PREV_MONTH,
    NULL AS AVG_LCY_MTD_PREV_MONTH
  FROM
    (
      SELECT
        'DUMMY-ACCOUNT' AS AC_NO,
        NVL(F.CLOSE_BAL_FCY, 0) AS AMT,
        F.CCY_CODE AS CCY,
        NVL(F.CLOSE_BAL_LCY, 0) AS LCY_AMT,
        A.AC_NO AS GL,
        B.BRANCH_CODE AS BRANCH_CODE,
        'DUMMY-CUSTOMER' AS CUST_NO,
        NULL AS ACCOUNT_CLASS,
        NULL AS MATURITY_DATE,
        NULL AS START_DATE,
        A.COMMERCIAL_SECTOR_CASA,
        'Facility' TYPE
      FROM
        FCT_GLBAL_D F,
        CORE.DIM_ACCOUNT A,
        CORE.DIM_BRANCH B
      WHERE
        F .ACCOUNT_SID = A .SID
        AND F .TRN_DT = V_REP_DATE
        AND A .AC_NO IN (
          '014110008',
          '014110015',
          '014110007',
          '014110019',
          '027211011',
          '027212002',
          '027211002',
          '027211036',
          '027212001'
        )
        AND F.BRANCH_SID = B.SID
        AND V_REP_DATE BETWEEN B.DATE_FROM
        AND B.DATE_TO
        AND V_REP_DATE BETWEEN A .DATE_FROM
        AND A .DATE_TO
    ) A1
    LEFT JOIN MIS.REF_BRANCH_DISTRICT_MANAGER DM ON DM.BRANCH_CODE = A1.BRANCH_CODE